import jsPDF from 'jspdf';

// Generate PDF Receipt for a single transaction
export const generatePDFReceipt = (transaction) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFillColor(0, 0, 0);
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text('PayFlow', 20, 25);
  
  doc.setFontSize(10);
  doc.text('Payment Receipt', 20, 33);
  
  // Reset text color
  doc.setTextColor(0, 0, 0);
  
  // Receipt details
  doc.setFontSize(16);
  doc.text('Payment Receipt', 20, 55);
  
  doc.setFontSize(11);
  
  // Transaction details
  const details = [
    { label: 'Transaction ID:', value: transaction.id },
    { label: 'Payer Name:', value: transaction.payer_name },
    { label: 'Amount:', value: `₹${transaction.amount}` },
    { label: 'Status:', value: transaction.status },
    { label: 'Note:', value: transaction.note || 'N/A' },
    { label: 'UPI ID:', value: transaction.upi_id },
    { label: 'Date:', value: new Date(transaction.created_at).toLocaleString() }
  ];
  
  let yPos = 70;
  details.forEach(item => {
    doc.setFont(undefined, 'bold');
    doc.text(item.label, 20, yPos);
    doc.setFont(undefined, 'normal');
    doc.text(item.value, 70, yPos);
    yPos += 10;
  });
  
  // Status badge
  yPos += 10;
  if (transaction.status === 'SUCCESS') {
    doc.setFillColor(34, 197, 94);
  } else if (transaction.status === 'FAILED') {
    doc.setFillColor(239, 68, 68);
  } else {
    doc.setFillColor(168, 85, 247);
  }
  doc.roundedRect(20, yPos, 40, 10, 2, 2, 'F');
  doc.setTextColor(255, 255, 255);
  doc.text(transaction.status, 25, yPos + 7);
  
  // Footer
  doc.setTextColor(128, 128, 128);
  doc.setFontSize(9);
  doc.text('Generated by PayFlow - Automated Payment Tracking System', 20, 280);
  doc.text(`Generated on: ${new Date().toLocaleString()}`, 20, 285);
  
  // Save the PDF
  doc.save(`PayFlow-Receipt-${transaction.id.slice(0, 8)}.pdf`);
};

// Export all transactions to CSV
export const exportToCSV = (transactions) => {
  if (transactions.length === 0) {
    alert('No transactions to export');
    return;
  }
  
  // CSV Headers
  const headers = ['Transaction ID', 'Payer Name', 'Amount', 'Status', 'Note', 'UPI ID', 'Created At', 'Updated At'];
  
  // CSV Rows
  const rows = transactions.map(txn => [
    txn.id,
    txn.payer_name,
    txn.amount,
    txn.status,
    txn.note || '',
    txn.upi_id,
    new Date(txn.created_at).toLocaleString(),
    new Date(txn.updated_at).toLocaleString()
  ]);
  
  // Combine headers and rows
  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
  ].join('\n');
  
  // Create blob and download
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  
  link.setAttribute('href', url);
  link.setAttribute('download', `PayFlow-Transactions-${new Date().toISOString().split('T')[0]}.csv`);
  link.style.visibility = 'hidden';
  
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

// Export filtered transactions to CSV
export const exportFilteredToCSV = (transactions, filters) => {
  const filename = `PayFlow-${filters.status || 'All'}-${filters.date || 'AllTime'}-${new Date().toISOString().split('T')[0]}.csv`;
  
  if (transactions.length === 0) {
    alert('No transactions to export');
    return;
  }
  
  const headers = ['Transaction ID', 'Payer Name', 'Amount', 'Status', 'Note', 'UPI ID', 'Created At'];
  
  const rows = transactions.map(txn => [
    txn.id,
    txn.payer_name,
    txn.amount,
    txn.status,
    txn.note || '',
    txn.upi_id,
    new Date(txn.created_at).toLocaleString()
  ]);
  
  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
  ].join('\n');
  
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  
  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  link.style.visibility = 'hidden';
  
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};